name: ansible-lint
on:
  push:
    branches: ["master"]

jobs:
  lint:
    name: Ansible lint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main

